name: overdrive
description: Working title
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: 1.2.0
  flame_audio: 1.2.0
  flame_behaviors: 0.1.1
  flame_forge2d: 0.12.0
  flex_color_scheme: ^5.0.1
  flutter:
    sdk: flutter
  overdrive_components:
    path: packages/overdrive_components

dev_dependencies:
  flame_lint: 0.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Monoton
      fonts:
        - asset: assets/fonts/Monoton-Regular.ttf