name: overdrive
description: Working title
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: 1.2.0
  flame_audio: 1.2.0
  flame_forge2d: 0.12.0
  flame_behaviors: 0.1.1
  overdrive_components:
    path: packages/overdrive_components
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: 0.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
