name: overdrive_components
description: Component library
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dartlin: 0.6.2
  flame: 1.2.0
  flame_behaviors: 0.1.1
  flame_forge2d: 0.12.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:
  flame_lint: 0.1.0
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

flutter:
  assets:
   - assets/images/
   - assets/images/title_screen/

flutter_gen:
  line_length: 80
  assets:
    package_parameter_enabled: true
