name: sandbox
description: Sandbox environment for components
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dashbook: 0.1.8
  flame: 1.2.0
  flutter:
    sdk: flutter
  overdrive_components:
    path: ../

dev_dependencies:
  flame_lint: 0.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
